### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sagotch** [mraiur/music-player#3]
Hello.

First, thank you for your work.

I forked your repo and started to make some modifications, but I realized that it does not contain any license allowing me to make these modifications available for everyone.

If you just do not care and do not know about licenses, MIT license basically allows everyone to do whatever they want with your work (and MIT license could be turn into another in later version of your program, even if versions released under MIT will remain MIT).

Cheers.

**Comment by netcarenepal** [comment]
![image](https://user-images.githubusercontent.com/43171809/54511692-d4b4cd00-4979-11e9-9425-348b12e01066.png)


but working well on local host running php 5.6, i have system which only supports php 5.4
