### ISSUE TITLE
How about to use HTML5 audio tag ?

### ISSUE THREAD

**Issue by nibreh** [mraiur/music-player#7]
Great app !

Do you think it's possible to use simple html5 audio tag ?
Like this  script : https://github.com/jaredblyth/php-html5-audio-jukebox

Cheers - thanks

**Comment by mraiur** [comment]
I added it in the first place but due to lack of browser support left it out.
I think to add it as a configuration option.

**Comment by nibreh** [comment]
Yes this will be nice ;) thanks for reply

**Comment by mraiur** [comment]
Added the native player support in v1.1. 
Thanks for the request.
