### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by azlux** [mraiur/music-player#8]
There are a error because you try to load <source src="{{currentSongPath}}" type="audio/mpeg">. Do there are a way to put an empty src when we load the page the first time ?

HTTP load failed with status 404 -->https://******.***/%7B%7BcurrentSongPath%7D%7D failed.

**Comment by azlux** [comment]
after check , you don't use this tag anymore, so it's still work if we remove the line <source src="{{currentSongPath}}" type="audio/mpeg">

**Comment by mraiur** [comment]
I am sorry but didn't understand the issue, can you please provide more information?

**Comment by azlux** [comment]
line 59-61 : 
<audio controls id="player" class="native-player">
<source src="{{currentSongPath}}" type="audio/mpeg">
</audio>

With the new feature "native player" no JavaScript will change "{{currentSongPath}}" so the browser will try to load a file named "{{currentSongPath}}" (it's give a 404 response)

**Comment by mraiur** [comment]
Fixed the problem when there is a s network downloading of the song and the end event not firing to jump on next song. ( bb7cad0649e621a579c8e319fd2ecab05601cd22 )
